version: '2'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - localhost:8888:80 # change ip if required
    volumes:
      - ./:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: indymockdatabaseaug2016
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    links:
      - db:db
    networks:
      - wordpress-network
  db:
    image: mysql:latest # or mariadb
    ports:
      - 127.0.0.1:8889:8889 # change ip if required
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: indymockdatabaseaug2016
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wordpress-network

networks:
  wordpress-network:
      driver: bridge